#!/usr/bin/env python
"""
Script to run NSGA-II multip objective optimization.

In the command line, run $ run_multiobj_optimization --gui
To select the size of the population append '--pop' to the command you run.
To select the number of the generations append '--gen' to the command you run.
To set the number of cores that the script will run, add --process <core-number>

To make further changes to the simulation, see 'sim_options' on line 114.
"""

import os
import argparse
import subprocess
from datetime import datetime
from pathlib import Path

import farms_pylog as pylog
from jmetal.algorithm.multiobjective.nsgaii import NSGAII
from jmetal.lab.visualization import Plot
try:
    from jmetal.operator import PolynomialMutation, SBXCrossover
except ImportError:
    from jmetal.operator.mutation import PolynomialMutation
    from jmetal.operator.crossover import SBXCrossover
from jmetal.util.evaluator import MultiprocessEvaluator
from jmetal.util.observer import VisualizerObserver
from jmetal.util.ranking import FastNonDominatedRanking
from jmetal.util.solution import (print_function_values_to_file,
                                  print_variables_to_file)
from jmetal.util.termination_criterion import StoppingByEvaluations

from NeuroMechFly.experiments.network_optimization import multiobj_optimization
from NeuroMechFly.experiments.network_optimization.multiobj_optimization import (
    WriteFullFrontToFileObserver,
    TrainingProgressObserver,
    load_warm_start_solutions,
)
from NeuroMechFly.utils.path_utils import get_neuromechfly_path

neuromechfly_path = get_neuromechfly_path()


def _current_git_branch():
    """Return current git branch name, or None if not in a repo / detached."""
    try:
        out = subprocess.run(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=neuromechfly_path,
            capture_output=True,
            text=True,
            timeout=2,
        )
        if out.returncode == 0 and out.stdout:
            return out.stdout.strip()
    except (subprocess.SubprocessError, FileNotFoundError):
        pass
    return None


def parse_args():
    """ Parse arguments from command line """
    branch = _current_git_branch()
    if branch == 'monsoon':
        default_pop, default_gen = 20, 50
    else:
        default_pop, default_gen = 4, 2

    parser = argparse.ArgumentParser()
    parser.add_argument('-g', '--gen', type=int, default=default_gen)
    parser.add_argument('-p', '--pop', type=int, default=default_pop)
    parser.add_argument('-n', '--process', type=int, default=8)
    parser.add_argument(
        '--controller',
        choices=['cpg', 'snn'],
        default='cpg',
        help='Controller type: cpg (default) or snn',
    )
    parser.add_argument(
        '--ground',
        choices=['ball', 'floor'],
        default='floor',
        help='Ground type: floor (default) or ball',
    )
    parser.add_argument(
        '--warm-start',
        type=str,
        default=None,
        metavar='PATH',
        help='Path to Phase 1 results (e.g. optimization_results/run_DrosophilaStability_...) '
             'to seed initial population. Best solutions by stability are used.',
    )
    parser.set_defaults(gui=False, profile=False)

    return parser.parse_args()

if __name__ == "__main__":
    """ Main """
    args = parse_args()
    n_pop = args.pop
    n_gen = args.gen
    # Problem
    max_evaluations = n_pop*n_gen
    print('Multi-objective optimization: will stop after exactly {} evaluations (pop={} × gen={}).'.format(
        max_evaluations, n_pop, n_gen))
    problem = multiobj_optimization.DrosophilaEvolution()
    problem.controller_type = args.controller
    problem.ground = args.ground
    branch = _current_git_branch()
    if branch != 'monsoon':
        problem.evaluation_run_time = 0.5

    if args.warm_start:
        warm_solutions = load_warm_start_solutions(
            args.warm_start,
            n_solutions=n_pop,
            sort_by='stability',
        )
        problem._initial_solutions = warm_solutions
        pylog.info(f'Warm start: loaded {len(warm_solutions)} solutions from {args.warm_start}')

    # Algorithm
    algorithm = NSGAII(
        problem=problem,
        population_size=n_pop,
        offspring_population_size=n_pop,
        mutation=PolynomialMutation(
            probability=1.0 / problem.number_of_variables,
            distribution_index=20,
        ),
        crossover=SBXCrossover(
            probability=0.9,
            distribution_index=15,
        ),
        population_evaluator=MultiprocessEvaluator(args.process),
        termination_criterion=StoppingByEvaluations(
            max_evaluations=max_evaluations
        ),
        # dominance_comparator=DominanceComparator()
    )
    # Output directory
    output_dir = os.path.join(
        neuromechfly_path,
        'scripts/neuromuscular_optimization'
    )

    # Results Dumping
    result_path = 'optimization_results/run_{}_var_{}_obj_{}_pop_{}_gen_{}_{}'.format(
            problem.name(),
            problem.number_of_variables,
            problem.number_of_objectives,
            n_pop,
            n_gen,
            datetime.now().strftime('%y%m%d_%H%M%S'),
    )
    algorithm.observable.register(
        observer=WriteFullFrontToFileObserver(
            output_directory=(
                os.path.join(output_dir, result_path)
            )
        )
    )

    # Visualisers
    algorithm.observable.register(
        observer=TrainingProgressObserver(
            max_evaluations=max_evaluations,
            population_size=n_pop,
        )
    )
    algorithm.observable.register(
        observer=VisualizerObserver(
            reference_front=problem.reference_front
        )
    )

    # Run optimisation
    algorithm.run()

    # Get results (jMetalPy API: result() not get_result())
    front = algorithm.result()
    ranking = FastNonDominatedRanking()
    # pareto_fronts = ranking.compute_ranking(front)

    # Plot front (skip if jMetalPy API mismatch, e.g. FloatSolution.number_of_objectives)
    try:
        plot_front = Plot(
            title='Pareto front approximation',
            reference_front=problem.reference_front,
            axis_labels=problem.obj_labels)
        plot_front.plot(front, filename=algorithm.get_name())
    except AttributeError:
        pylog.warning('Skipping Pareto front plot (jMetalPy API may have changed)')

    # Save results of the latest generation to a .txt file
    print_function_values_to_file(front,  os.path.join(output_dir,'FUN.txt'))
    print_variables_to_file(front,  os.path.join(output_dir,'VAR.txt'))

    # Move the config file inside the results directory
    Path(os.path.join(output_dir, 'optimization_results/CONFIG.yaml')).rename(os.path.join(output_dir, result_path, 'CONFIG.yaml'))

    print('Algorithm (continuous problem): ' + algorithm.get_name())
    print('Problem: ' + problem.name())
    print('Computing time: ' + str(algorithm.total_computing_time*1/60))
